### DISCUSSION TITLE
Add back support for custom policies in starboard-policies-config

### DISCUSSION THREAD

**Discussion by yurrriq** [aquasecurity/starboard#1143] [Development]
ref: https://aquasecurity.github.io/starboard/v0.15.4/tutorials/writing-custom-configuration-audit-policies/

Previously, with the Conftest plugin, one was able to add custom policies using the Helm chart as follows:

```yaml
conftest:
  library: {}
    # kubernetes.rego: |
    #   << REGO >>
    # utils.rego: |
    #   << REGO >>
  policy: {}
    # access_to_host_pid:
    #   rego: |
    #     << REGO >>
    #   kinds: Workload
    # configmap_with_sensitive_data:
    #   rego: |
    #     << REGO >>
    #   kinds: ConfigMap
```

Now, with the built-in scanner, I'd like to inject custom policies similarly when using the Helm chart. For now, I'll use `--post-renderer`, but I'd like it to be a feature of the chart.

PR forthcoming.
