### DISCUSSION TITLE
Scan registry images before pods are deployed

### DISCUSSION THREAD

**Discussion by cjnosal** [aquasecurity/starboard#464] [Development]
The starboard operator currently watches pods to trigger a scan. In some cases it's desirable to scan an artifact before the code is deployed and running.

A new `ArtifactReference` CRD could be defined:
```
kind: ArtifactReference
spec:
  repository: myregistry.com/myrepo
  tag: 1.16
  digest: # optional if tag not specified
  secretName: # optional - for private registries
```
A new controller would then trigger a scan when a new ArtifactReference instance is created. The initial implementation could rely on the operator to update the CRD when a new image is in the registry. 

The functionality could be extended to support polling the registry for new tags or digests if neither is specified. This may require a status field for the reconciler to capture what was scanned:
```
kind: ArtifactReference
spec:
  repository: myregistry.com/myrepo
  secretName: # optional - for private registries
status:
  scannedDigest: sha256:...
```

The implementation could largely reuse the logic of `VulnerabilityReportReconciler.reconcilePods` (read the artifact reference, check ownership, check for existing VulnerabilityReport/Job, check throttling, submit the scan). The usage of `corev1.PodSpec` and `ContainerImages` may need to be abstracted as this flow would not have a Pod or a container name.
