### DISCUSSION TITLE
POC: Vulnerability scanners using image digest

### DISCUSSION THREAD

**Discussion by danielpacak** [aquasecurity/starboard#707] [Development]
Currently vulnerability scanners are supposed to scan container images by image reference set in a pod template. However, this approach does not allow us to scan the actual image that was pulled by a container runtime at pod creation time. For example, container runtime might be configured to pull images from a registry mirror. What's more, in case of so called mutant tags,  the image reference may not be deterministic and images pulled at pod creation time might be different.

We can describe this change as taking the image reference from `{.status.containerStatuses[0].imageID}` instead of `{.spec.containers[0].image}`. Looking at the following example, we want to pass  `docker.io/library/nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c` instead of `nginx:16` to a vulnerability scanner.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx:1.16
    imagePullPolicy: IfNotPresent
    name: nginx
  nodeName: kind-control-plane
  restartPolicy: Always
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-14T19:27:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-14T19:27:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-14T19:27:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-14T19:27:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://67cd22fb4e45afa54a94577ea2bb41e3c650bb3ce84bbbc90edf03e9230c4cda
    image: docker.io/library/nginx:1.16
    imageID: docker.io/library/nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-14T19:27:49Z"
  hostIP: 172.18.0.2
  phase: Running
  podIP: 10.244.0.18
  podIPs:
  - ip: 10.244.0.18
  qosClass: BestEffort
  startTime: "2021-09-14T19:27:09Z"
```

Notice that scan by image digest implies changes to life cycle of VulnerabilityReport instances, which are currently stored / owned by K8s workload controllers, e.g. ReplicaSet, ReplicationController or StatefulSets.  
In scope of this POC we can store VulnerabilityReports at Pod level to minimise the scope of changes.
Also we do not have to worry about downstream integrations such as Octant plugin or LENS extension
