### DISCUSSION TITLE
Starboard deployment managed through ArgoCD not working

### DISCUSSION THREAD

**Discussion by AnaisUrlichs** [aquasecurity/starboard#991] [Questions & Help]
I used this guide by ArgoCD to deploy Starboard: https://argo-cd.readthedocs.io/en/stable/user-guide/helm/

Here is my YAML used to deploy:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard
  namespace: argocd
spec:
  project: default
  source:
    chart: starboard-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.9.1
    helm:
      releaseName: starboard
  destination:
    server: https://kubernetes.default.svc
    namespace: starboard-system
```

When I deploy starboard through Helm directly without ArgoCD, it works like expected.
However, with ArgoCD, the operator pod would spin up and then Crash after a few minutes, the logs show the following errors:
![Untitled](https://user-images.githubusercontent.com/33576047/156358335-7852facd-e073-4c3e-8713-104b9c31ad23.png)

Any ideas on how I can fix it or further debug?
