### ISSUE TITLE
Kubernetes users with the role admin are forbidden to list vulnerabilityreports and configauditreports

### ISSUE THREAD

**Issue by elchenberg** [aquasecurity/starboard#1080]
**What steps did you take and what happened:**

I installed starboard-operator in a Kubernetes cluster using the Helm chart. Now `kubectl --as=namespace-admin --namespace=namespace-of-namespace-admin get all` throws errors:

```
Error from server (Forbidden): vulnerabilityreports.aquasecurity.github.io is forbidden: User "namespace-admin" cannot list resource "vulnerabilityreports" in API group "aquasecurity.github.io" in the namespace "namespace-of-namespace-admin"
Error from server (Forbidden): configauditreports.aquasecurity.github.io is forbidden: User "namespace-admin" cannot list resource "configauditreports" in API group "aquasecurity.github.io" in the namespace "namespace-of-namespace-admin"
```

Could this be an issue with Starboard Operator or did I miss something when I installed it in my cluster?

**What did you expect to happen:**

No errors when users want to list resources in their own namespace.

**Anything else you would like to add:**

- The namespace is empty.
- The user has the role `admin` <https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles>.
- Users with the role `cluster-admin` do not experience this issue.

**Environment:**

- Starboard Operator Helm release version: v0.9.1
- Starboard Operator version: v0.14.1
- Kubernetes version: v1.23.5

**Comment by elchenberg** [comment]
I was able to solve this issue using the following ClusterRole:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: starboard-crd-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources: ["configauditreports", "vulnerabilityreports"]
    verbs: ["get", "list", "watch"]
```
