### ISSUE TITLE
Kube-hunter cannot overwrite report named "cluster"  when running in a CronJob

### ISSUE THREAD

**Issue by sylus** [aquasecurity/starboard#109]
**What steps did you take and what happened:**

It seems I can't run kube-hunter in a cron job because on the second run it complains that cluster exists. I was hoping I could run kube-hunter continuously on a set interval in case starboard ever got updated and there were new check.

Love the tool thanks so much!

**What did you expect to happen:**

That the next cron run will succeed just like kube-bench

**Anything else you would like to add:**

N/A

**Environment:**

- Starboard version (use `starboard version`): v0.2.5
- Kubernetes version (use `kubectl version`): v1.15.10
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): 18.04

**Comment by danielpacak** [comment]
Hi @sylus ! Thank you for reporting this issue. However, I need more details to help you as I don't quite understand you case:
- Which version of the starboard binary did you use? We did some changes to create or update kube bench and kube hunter reports, which are not released yet; only available on master.
- Which exact Starboard command are you running? Is it `starboard kube-bench`?
- Could you share a cron job descriptor (YAML or JSON) so I could reproduce on my end?

**Comment by sylus** [comment]
Hi there,

The version is starboard 0.2.5 and I attached a picture showing the error and the cronjob spec.

![Screen Shot 2020-08-12 at 10 45 19 AM](https://user-images.githubusercontent.com/984304/90029562-02926400-dc89-11ea-82ec-e901825aeeb7.png)

```
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: starboard-kube-hunter
  namespace: starboard
spec:
  schedule: 15 4 * * *
  startingDeadlineSeconds: 60
  concurrencyPolicy: Replace
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: starboard-kube-hunter
        spec:
          containers:
            - name: starboard
              image: 'statcan/starboard:v0.2.5'
              command:
                - starboard
              args:
                - kube-hunter
                - '-v3'
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
status:
  lastScheduleTime: '2020-08-12T04:15:00Z'
```
