### ISSUE TITLE
The get vulnerabilities subcommand does not respect global flags (e.g. --kubeconfig)

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#142]
**What steps did you take and what happened:**

The global flags to configure client-go are not respected by the `get vulnerabilities` subcommand:

```
$ starboard --kubeconfig /path/to/kube/config \
    get vulnerabilities pod/nginx-tn2wq \
    -o yaml
```

**What did you expect to happen:**

The `--kubeconfig` flag and other global flags to be passed to the get vulnerabilities subcommand.

**Anything else you would like to add:**

N/A

**Environment:**

- Starboard version (use `starboard version`): 0.2.6
- Kubernetes version (use `kubectl version`): Any
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Any

**Comment by danielpacak** [comment]
@krisctl Are you available to work on this one? If not please let us know if we should leave it as unassigned.

**Comment by neha-viswanathan** [comment]
@danielpacak I tried this out, and it seems like the ordering of the `kubeconfig` flag is an issue with your example:
```
kubectl starboard --kubeconfig=/path/to/my-kubeconfig get vulnerabilities pod/pod-xyz -o yaml                                      
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

But the below one seems to work with passing the `kubeconfig` flag after the vulnerabilities subcommand.
```
kubectl starboard get vulnerabilities --kubeconfig=/path/to/my-kubeconfig pod/pod-xyz -o yaml
apiVersion: v1
items:
- apiVersion: aquasecurity.github.io/v1alpha1
  kind: VulnerabilityReport
  metadata:
    creationTimestamp: "2020-10-06T23:04:00Z"
    generation: 1
    labels:
-----
```
