### ISSUE TITLE
Set SecurityContext for pods created by scan jobs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#163]
To implement least privileged principle we should explicitly set SecurityContexts<sup>[1]</sup> on pod templates for each scan job. Such SecurityContext should reflect minimal privileges to run a given scanner. The goal here is to review required permissions and set them explicitly for each pod template comprising a scan job descriptor.

[1]: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by akath19** [comment]
@danielpacak I'd like to pick this one up, here's my suggested SecurityContext:

Pod Level:
```
securityContext:
   runAsUser: 1900
   runAsGroup: 1900
   fsGroup: 1900
   runAsNonRoot: true
```

Container level:

```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
      drop:
       - all
  privileged: false
  readOnlyRootFilesystem: false
````

I've tested this with trivy & polaris jobs, I haven't tested this with kube-bench/hunter jobs yet.
