### ISSUE TITLE
Manage pods controlled by Argo Workflow

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#373]
Pods created by [Argo] controllers are owned by Workflow objects. In this case Starboard fails to resolve the owner reference and cannot save a security report in etcd.

Pods controlled by Workflows or any other non-standard controller should be treated as unmanaged pods. Even though we could read an instance of Workflow in a generic way and set it as the owner of a VulnerabilityReport, this would require additional RBAC config, which depends on third-party software running in the cluster.

```yaml
metadata:
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: hello-world-r99sq
    uid: 7791f1e4-9486-4b38-a09f-82806b57c4ae
```

[Argo]: https://github.com/argoproj/argo/
