### ISSUE TITLE
Assign VulnerabilityReports to CronJob instead of Jobs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#451]
**What steps did you take and what happened:**

Create a CronJob:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

Deploy Starboard Operator and check VulnerabilityReports that are created for the Cron Job:

```console
$ kubectl tree cj hello
NAMESPACE  NAME                                                READY  REASON        AGE
default    CronJob/hello                                       -                    6m54s
default    ├─ConfigAuditReport/cronjob-hello                   -                    6m50s
default    ├─Job/hello-1616523840                              -                    2m47s
default    │ ├─Pod/hello-1616523840-f92zr                      False  PodCompleted  2m47s
default    │ └─VulnerabilityReport/job-hello-1616523840-hello  -                    2m40s
default    ├─Job/hello-1616523900                              -                    107s
default    │ ├─Pod/hello-1616523900-9rskh                      False  PodCompleted  107s
default    │ └─VulnerabilityReport/job-hello-1616523900-hello  -                    100s
default    └─Job/hello-1616523960                              -                    47s
default      ├─Pod/hello-1616523960-z6nlc                      False  PodCompleted  47s
default      └─VulnerabilityReport/job-hello-1616523960-hello  -                    39s
```

VulnerabilityReports are owned by Jobs, whereas Jobs are created and deleted based on Schedule, which can be quite frequent. On the other hand each CronJob has the PodTemplateSpec that does not change so we could save only one VulnerabilityReport and associate it with the CronJob.

**What did you expect to happen:**

A VulnerabilityReport is owned by a CronJob:

```console
$ kubectl tree cj hello
NAMESPACE  NAME                                                READY  REASON        AGE
default    CronJob/hello                                       -                    6m54s
default    ├─ConfigAuditReport/cronjob-hello                   -                    6m50s
default    ├─VulnerabilityReport/cronjob-hello                 -                    4m50s
default    ├─Job/hello-1616523840                              -                    2m47s
default    │ └─Pod/hello-1616523840-f92zr                      False  PodCompleted  2m47s
default    ├─Job/hello-1616523900                              -                    107s
default    │ └─Pod/hello-1616523900-9rskh                      False  PodCompleted  107s
default    └─Job/hello-1616523960                              -                    47s
default      └─Pod/hello-1616523960-z6nlc                      False  PodCompleted  47s
```

**Anything else you would like to add:**

The PodSpec of a CronJob does not change so there's no point in rescanning individual Jobs.

Fixing this issue would be easier once #414 is resolved
