### ISSUE TITLE
staboard-operator cannot pull images from ECR

### ISSUE THREAD

**Issue by steevi** [aquasecurity/starboard#468]
**What steps did you take and what happened:**
Install starboard-operator based on 0.10rc2

the rbac section in the values file is as follows:
```
    rbac:
      create: true
    serviceAccount:
      # Specifies whether a service account should be created.
      create: true
      annotations: 
        eks.amazonaws.com/role-arn: arn:aws:iam::XXX
      # name specifies the name of the k8s Service Account. If not set and create is
      # true, a name is generated using the fullname template.
      name: ""
```

Can see vulnerability reports being generated in all namespaces for public images but not for private images hosted in ECR

Seems the annations are appended in the sa, but still it doesn't work

The iam policy has been created based on the following link
https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html#AmazonEC2ContainerRegistryReadOnly

**What did you expect to happen:**
see vulnerabilitry reports for images hosted in private ECR

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Starboard version: 0.10-rc2
- Kubernetes version: EKS 1.18
