### ISSUE TITLE
Wrong arguments for Trivy client

### ISSUE THREAD

**Issue by bgoareguer** [aquasecurity/starboard#504]
**What steps did you take and what happened:**

Deploy Starboard Operator with the Helm chart with the following values:
```
values:
    targetNamespaces: default
    trivy:
      mode: ClientServer
      serverURL: http://trivy:4954
      httpProxy: http://proxy:3128
      httpsProxy: http://proxy:3128
      noProxy: localhost,127.0.0.1,proxy,trivy
```

**What did you expect to happen:**
I expected the images to be successfully scanned with the Trivy Server and VulnerabilityReports resources to be created.

** Actual behavior **
The images are not scanned (no job created) and no VulnerabilityReport resource is created.

**Anything else you would like to add:**

Here is an extract of the logs of the Starbord Operator pod:
```
Incorrect Usage: flag provided but not defined: -quiet
```

It seems the `--quiet` flag is wrongly positioned after the `client` subcommand: https://github.com/aquasecurity/starboard/blob/v0.10.0/pkg/plugin/trivy/plugin.go#L492

Current (broken) command:
```
trivy client --quiet --format json --remote trivyServerURL
```

Expected command:
```
trivy --quiet client --format json --remote trivyServerURL
```

**Environment:**

- Starboard version (use `starboard version`): 0.10.0
- Kubernetes version (use `kubectl version`): 1.20.4
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Ubuntu 16.04
