### ISSUE TITLE
Fix RBAC config when OwnerReferencesPermissionEnforcement admission controller plugin is enabled

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#514]
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement

```yaml
# Save this to ~/tmp/kind-config/ocp-kind.config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ocp-kind
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,OwnerReferencesPermissionEnforcement
- role: worker
- role: worker
```

```
kind create cluster --config ~/tmp/kind-config/ocp-kind.config.yaml
```

```
"writing report: ciskubebenchreports.aquasecurity.github.io \"ocp-kind-worker\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"
```
