### ISSUE TITLE
Try getting error message from failing scan jobs

### ISSUE THREAD

**Issue by danielpacak** [aquasecurity/starboard#52]
It's inevitable that some scan jobs will fail. In such case the Scanner CLI does not provide informative error message beyond Job status. What's more, Starboard cleans the Job so it's not possible to check Pod logs and see what was the root cause of the problem.

**Comment by danielpacak** [comment]
I'm going to leverage container termination messages<sup>[1]</sup> to get insights into failing jobs. In the following example the container state has the message property, which describes the problem:

```yaml
containerStatuses:
  - containerID: docker://ff811ff415b4d8bda909a61a5088b309fb43025eadea7d09fd2acc58ad2e72dd
    image: aquasec/trivy:0.9.1
    imageID: docker-pullable://aquasec/trivy@sha256:5020dac24a63ef4f24452a0c63ebbfe93a5309e40f6353d1ee8221d2184ee954
    lastState: {}
    name: nginx
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://ff811ff415b4d8bda909a61a5088b309fb43025eadea7d09fd2acc58ad2e72dd
        exitCode: 1
        finishedAt: "2020-06-18T08:56:52Z"
        message: "2020-06-18T08:56:52.122Z\t\e[31mFATAL\e[0m\tunable to initialize
          a scanner: unable to initialize a docker scanner: 2 errors occurred:\n\t*
          unable to inspect the image (core.harbor.domain/library/nginx:1.16): Cannot
          connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker
          daemon running?\n\t* Get https://core.harbor.domain/v2/: x509: certificate
          signed by unknown authority\n\n\n"
        reason: Error
        startedAt: "2020-06-18T08:56:52Z"
```

[1]: https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/
