### ISSUE TITLE
Forbidden: seccomp may not be set

### ISSUE THREAD

**Issue by schizoid90** [aquasecurity/starboard#637]
**What steps did you take and what happened:**

I've installed Starboard via Helm and everything seems to work fine except the cisbenchmark job. I am receiving an error about seccomp. There are some other errors regarding PSP but as far as I can tell, these should be fixed.

```
Error creating: pods "scan-cisbenchmark-7dd584d745-" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0].hostPath.pathPrefix: Invalid value: "/var/lib/etcd": is not allowed to be used spec.volumes[1].hostPath.pathPrefix: Invalid value: "/var/lib/kubelet": is not allowed to be used spec.volumes[2].hostPath.pathPrefix: Invalid value: "/etc/systemd": is not allowed to be used spec.volumes[3].hostPath.pathPrefix: Invalid value: "/etc/kubernetes": is not allowed to be used spec.volumes[4].hostPath.pathPrefix: Invalid value: "/usr/bin": is not allowed to be used pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kube-bench]: Forbidden: seccomp may not be set pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kube-bench]: Forbidden: seccomp may not be set]
  Warning  FailedCreate  2m39s (x161 over 25h)  job-controller  Error creating: pods "scan-cisbenchmark-7dd584d745-" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kube-bench]: Forbidden: seccomp may not be set pod.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: Forbidden: seccomp may not be set spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0].hostPath.pathPrefix: Invalid value: "/var/lib/etcd": is not allowed to be used spec.volumes[1].hostPath.pathPrefix: Invalid value: "/var/lib/kubelet": is not allowed to be used spec.volumes[2].hostPath.pathPrefix: Invalid value: "/etc/systemd": is not allowed to be used spec.volumes[3].hostPath.pathPrefix: Invalid value: "/etc/kubernetes": is not allowed to be used spec.volumes[4].hostPath.pathPrefix: Invalid value: "/usr/bin": is not allowed to be used pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/kube-bench]: Forbidden: seccomp may not be set]
```

**What did you expect to happen:**

Job should run OK

**Anything else you would like to add:**
I'm not sure if there are any seccomp profiles on the server, I certainly haven't configured any but are there any default ones? Is there a way to configure this as part of the deployment?

PSP
```
spec:
  allowPrivilegeEscalation: false
  allowedHostPaths:
  - pathPrefix: /var/lib/etcd
    readOnly: true
  - pathPrefix: /var/lib/kubelet
    readOnly: true
  - pathPrefix: /etc/systemd
    readOnly: true
  - pathPrefix: /etc/kubernetes
    readOnly: true
  - pathPrefix: /usr/bin
    readOnly: true
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostPID: true
  runAsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
  - secret
  - projected
```

RBAC for allowing the use of the PSP

```
Name:         psp-kube-bench
Labels:       kustomize.toolkit.fluxcd.io/checksum=f219c2681fddbe5abdebd8a3344fbd77e950df09
              kustomize.toolkit.fluxcd.io/name=on-prem
              kustomize.toolkit.fluxcd.io/namespace=cicd
Annotations:  <none>
Role:
  Kind:  Role
  Name:  psp-kube-bench
Subjects:
  Kind            Name                          Namespace
  ----            ----                          ---------
  ServiceAccount  starboard-starboard-operator  security
  ServiceAccount  default                       security
```

```
kubectl -n security describe role
Name:         psp-kube-bench
Labels:       kustomize.toolkit.fluxcd.io/checksum=f219c2681fddbe5abdebd8a3344fbd77e950df09
              kustomize.toolkit.fluxcd.io/name=on-prem
              kustomize.toolkit.fluxcd.io/namespace=cicd
Annotations:  <none>
PolicyRule:
  Resources                       Non-Resource URLs  Resource Names     Verbs
  ---------                       -----------------  --------------     -----
  podsecuritypolicies.extensions  []                 [aqua-kube-bench]  [use]
```

**Environment:**

- Starboard version (use `starboard version`): 
`Starboard Version: {Version:0.10.3 Commit:5bd33431a239b98be4a3287563b8664a9b3d5707 Date:2021-05-14T12:20:34Z}`
- Kubernetes version (use `kubectl version`): 
`kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}`
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
`Ubutnu 18.04`
