### ISSUE TITLE
starboard-trivy-config secret with empty data section

### ISSUE THREAD

**Issue by dschunack** [aquasecurity/starboard#685]
**What steps did you take and what happened:**
The data section of the starboard-trivy-config secret was empty, due to missing idents.

Helm values

```yaml
trivy:
  mode: ClientServer
  severity: "MEDIUM,HIGH,CRITICAL"
  ignoreUnfixed: "true"
  nodeSelector:
    kubernetes.io/os: linux
  serverURL: "http://trivy-server:8080"
  serverToken: "testtoken"
```

```yaml
kubectl -n starboard-operator describe secrets starboard-trivy-config
Name:         starboard-trivy-config
Namespace:    starboard-operator
Labels:       app.kubernetes.io/instance=starboard-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=starboard-operator
              app.kubernetes.io/version=0.11.0
              helm.sh/chart=starboard-operator-0.6.0
Annotations:  meta.helm.sh/release-name: starboard-operator
              meta.helm.sh/release-namespace: starboard-operator

Type:  Opaque

Data
====

```

**Anything else you would like to add:**

I created a PR to fix the issue.
