### ISSUE TITLE
Starboard Vulnerability scan fails to process scan job when auth is missing in registry secret

### ISSUE THREAD

**Issue by deven0t** [aquasecurity/starboard#855]
If user creates a registry secret without auth mentioned in it, then starboard fails with error 
`error: reading .dockerconfigjson field of "xx/xx-registry" secret: expected username and password concatenated with a colon (:)`
even though registry secret has username and password specified in dockerconfigjson, auth part is missing in the detail.
eg: 
```yaml
"harbor.domain": {
Username: "admin",
Password: "Harbor12345",
}
```
We can add additional logic to consider username and password if auth is empty.
