### ISSUE TITLE
Starboard Operator: Broken CVE Links in Vulnerability Reports

### ISSUE THREAD

**Issue by elchenberg** [aquasecurity/starboard#957]
**What steps did you take and what happened:**

I deployed the starboard-operator using the Helm chart v0.9.1.

The `primaryLink`s of the vulnerability reports are broken (404 page not found).

Example report:

```yaml
report:
  artifact:
    repository: aquasecurity/trivy
    tag: 0.22.0
  registry:
    server: ghcr.io
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.22.0
  summary:
    criticalCount: 6
    highCount: 0
    lowCount: 0
    mediumCount: 0
    noneCount: 0
    unknownCount: 0
  updateTimestamp: "2022-02-14T14:11:43Z"
  vulnerabilities:
  - fixedVersion: 2.4.3-r0
    installedVersion: 2.4.1-r0
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-22822
    resource: expat
    score: 9.8
    severity: CRITICAL
    title: 'expat: Integer overflow in addBinding in xmlparse.c'
    vulnerabilityID: CVE-2022-22822
  - fixedVersion: 2.4.3-r0
    installedVersion: 2.4.1-r0
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-22823
    resource: expat
    score: 9.8
    severity: CRITICAL
    title: 'expat: Integer overflow in build_model in xmlparse.c'
    vulnerabilityID: CVE-2022-22823
  - fixedVersion: 2.4.3-r0
    installedVersion: 2.4.1-r0
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-22824
    resource: expat
    score: 9.8
    severity: CRITICAL
    title: 'expat: Integer overflow in defineAttribute in xmlparse.c'
    vulnerabilityID: CVE-2022-22824
  - fixedVersion: 2.4.4-r0
    installedVersion: 2.4.1-r0
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-23852
    resource: expat
    score: 9.8
    severity: CRITICAL
    title: 'expat: integer overflow in function XML_GetBuffer'
    vulnerabilityID: CVE-2022-23852
  - fixedVersion: 2.4.4-r0
    installedVersion: 2.4.1-r0
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2022-23990
    resource: expat
    score: 9.8
    severity: CRITICAL
    title: 'expat: integer overflow in the doProlog function'
    vulnerabilityID: CVE-2022-23990
  - fixedVersion: 1.5.9
    installedVersion: v1.5.8
    links: []
    primaryLink: https://avd.aquasec.com/nvd/cve-2021-43816
    resource: github.com/containerd/containerd
    score: 6.7
    severity: CRITICAL
    title: 'containerd: Unprivileged pod may bind mount any privileged regular file
      on disk'
    vulnerabilityID: CVE-2021-43816
```
**Environment:**

- Starboard version (use `starboard version`):

starboard-operator: `"buildInfo":{"Version":"0.14.1","Commit":"5672fd4a4d608d9b094802098f3e950ec396ff51","Date":"2022-01-25T17:38:43Z","Executable":""}}`

- Kubernetes version (use `kubectl version`):

`Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}`

- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):
